"""Initial migration

Revision ID: bfa1dfe15ead
Revises: 
Create Date: 2025-03-14 22:59:43.269742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa1dfe15ead'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'books',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sa.String, nullable=False),
        sa.Column('author', sa.String, nullable=False),
        sa.Column('copies_available', sa.Integer, default=1),
    )

    op.create_table(
        'members',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String, nullable=False),
        sa.Column('membership_fee', sa.Float, default=0.0),
    )

    op.create_table(
        'borrows',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('book_id', sa.Integer, sa.ForeignKey('books.id')),
        sa.Column('member_id', sa.Integer, sa.ForeignKey('members.id')),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
